apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zfs-zvol
  namespace: democratic-csi
spec:
  interval: 30m
  chart:
    spec:
      chart: democratic-csi
      version: 0.15.1
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
        namespace: democratic-csi
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: zfs-zvol-values
      valuesKey: values.yaml