apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./fluxcd/authentik
  - ./fluxcd/cdi
  - ./fluxcd/cnpg
  - ./fluxcd/democratic-csi
  - ./fluxcd/flux-system
  - ./fluxcd/jellyfin
  - ./fluxcd/kubevirt
  - ./fluxcd/sunshine