apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./authentik
  - ./grafana-k8s-monitoring
  - ./cdi
  - ./cnpg
  - ./democratic-csi
  - ./immich
  - ./flux-system
  - ./jellyfin
  - ./kubevirt