apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-blueprints
  namespace: authentik
data:
  minimal-test.yaml: |
    version: 1
    entries:
      - model: authentik_core.group
        identifiers:
          name: blueprint-test-20260311
        attrs:
          name: blueprint-test-20260311
  jellyfin.yaml: |
    version: 1

    metadata:
      name: jellyfin-minimal
      labels:
        app: jellyfin
        managed-by: blueprint

    entries:

    # ----------------------------
    # Groups
    # ----------------------------

    - model: authentik_core.group
      id: group-jellyfin-users
      identifiers:
        name: JellyfinUsers
      attrs:
        name: JellyfinUsers

    # ----------------------------
    # Service Account
    # ----------------------------

    - model: authentik_core.user
      id: user-jellyfin-bind
      identifiers:
        username: jellyfin-bind
      attrs:
        username: jellyfin-bind
        name: Jellyfin LDAP Bind
        is_active: true
        type: service_account

    # ----------------------------
    # LDAP Provider
    # ----------------------------

    - model: authentik_providers_ldap.ldapprovider
      id: provider-jellyfin
      identifiers:
        name: Provider for Jellyfin
      attrs:
        name: Provider for Jellyfin
        base_dn: dc=authentik,dc=local
        bind_mode: cached
        search_group: !KeyOf group-jellyfin-users

    # ----------------------------
    # Application
    # ----------------------------

    - model: authentik_core.application
      id: app-jellyfin
      identifiers:
        slug: jellyfin
      attrs:
        name: Jellyfin
        slug: jellyfin
        provider: !KeyOf provider-jellyfin

    # ----------------------------
    # LDAP Outpost
    # ----------------------------

    - model: authentik_outposts.outpost
      id: outpost-ldap
      identifiers:
        name: LDAP
      attrs:
        name: LDAP
        type: ldap
        providers:
          - !KeyOf provider-jellyfin