apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-blueprints
  namespace: authentik
data:
  minimal-test.yaml: |
    version: 1
    entries:
      - model: authentik_core.group
        attrs:
          attributes: {}
          is_superuser: false
          name: JellyfinUsers
          parents: []
          roles: []
        conditions: []
        identifiers:
          name: group-jellyfinusers
        permissions: []
        state: present

      - model: authentik_rbac.role
        id: role-ldapsearch
        identifiers:
          name: LDAP Search
        attrs:
          name: LDAP Search
        state: present

      - model: authentik_core.user
        identifiers:
          username: jellyfin-bind
        attrs:
          username: jellyfin-bind
          name: jellyfin-bind
          path: goauthentik.io/service-accounts
          type: service_account
          roles:
            - !KeyOf role-ldapsearch
        state: present

      - model: authentik_core.application
        attrs:
          backchannel_providers: []
          group: ''
          meta_description: ''
          meta_icon: ''
          meta_launch_url: ''
          meta_publisher: ''
          name: Jellyfin
          open_in_new_tab: false
          policy_engine_mode: any
          provider: 2
          slug: jellyfin
        conditions: []
        id: application-jellyfin
        identifiers:
          slug: jellyfin
        permissions: []
        state: present