apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-blueprints
  namespace: authentik
data:
  minimal-test.yaml: |
    version: 1
    entries:
      - model: authentik_core.group
        attrs:
          attributes: {}
          is_superuser: false
          name: JellyfinUsers
          parents: []
          roles: []
        conditions: []
        identifiers:
          name: group-jellyfinusers
        permissions: []
        state: present

      - model: authentik_rbac.role
        id: role-ldapsearch
        identifiers:
          name: LDAP Search
        attrs:
          name: LDAP Search
        state: present

      - model: authentik_core.user
        identifiers:
          username: jellyfin-bind
        attrs:
          username: jellyfin-bind
          name: jellyfin-bind
          path: goauthentik.io/service-accounts
          type: service_account
          roles:
            - !KeyOf role-ldapsearch
        state: present

      - model: authentik_flows.flow
        attrs:
          authentication: none
          background: ''
          compatibility_mode: false
          denied_action: message_continue
          designation: authentication
          layout: stacked
          policy_engine_mode: any
          slug: default-authentication-flow
          title: Welcome to authentik!
        conditions: []
        identifiers:
          name: Welcome to authentik!
        id: default-authentication-flow
        permissions: []
        state: present

      - model: authentik_flows.flow
        attrs:
          authentication: none
          background: ''
          compatibility_mode: false
          denied_action: message_continue
          designation: invalidation
          layout: stacked
          policy_engine_mode: any
          slug: default-invalidation-flow
          title: Default Invalidation Flow
        conditions: []
        identifiers:
          name: Logout
        id: default-invalidation-flow
        permissions: []
        state: present
        
      - model: authentik_providers_ldap.ldapprovider
        attrs:
          authentication_flow: null
          authorization_flow: !KeyOf default-authentication-flow
          base_dn: DC=ldap,DC=goauthentik,DC=io
          bind_mode: direct
          certificate: null
          gid_start_number: 4000
          # default-invalidation-flow
          invalidation_flow: !KeyOf default-invalidation-flow
          mfa_support: false
          name: Provider for Jellyfin
          property_mappings: []
          search_mode: direct
          tls_server_name: ''
          uid_start_number: 2000
        conditions: []
        identifiers:
          name: Provider for Jellyfin
        id: provider-ldap
        permissions: []
        state: present

      - model: authentik_core.application
        attrs:
          backchannel_providers: []
          group: ''
          meta_description: ''
          meta_icon: ''
          meta_launch_url: ''
          meta_publisher: ''
          name: Jellyfin
          open_in_new_tab: false
          policy_engine_mode: any
          provider: !KeyOf provider-ldap
          slug: jellyfin
        conditions: []
        id: application-jellyfin
        identifiers:
          slug: jellyfin
        permissions: []
        state: present