apiVersion: v1
kind: Secret
metadata:
    name: authentik-config
    namespace: authentik
type: Opaque
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:aSvW9tLNYio8GEy8eeB9e5IT0XQ=,iv:Y1lqSYsJN3fyk3XMoMvRt9Ot7fEEsWb6pWhOZjaN9EY=,tag:BiqADk33+V9+K+wTK70DiA==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:w+p3x0LGFpXuE0BDkqtlLGjxEVU=,iv:HA8Ogh/Hnks2BFm3ASsILfwoy/XhYnU585nnVFOUe5A=,tag:nIA8l0H6P7BmY44RcP1G/w==,type:str]
sops:
    lastmodified: "2026-03-10T04:59:30Z"
    mac: ENC[AES256_GCM,data:wdKEE+iFxD6u5hEFxgWlXJq4+Nn2hOOxrVM2cN9DqY5lWns6ljVDL3I6L0CNhIRhUxqezFoLRvyJ8jbtbhYAAFK/iYTNeU5r+la18R63hFBH95ntj7AfrZ5PLdyiCxOcaJzNH0u6ALxhjrQbNUdbOZCptkIOnUIeXY8JJ9gh7pU=,iv:qx60A2fyyy7CqqmhjCFSuoG0R6KXBnfrRIL8eO9TZ20=,tag:GBaL507CMRRjCgvB7ff9ug==,type:str]
    pgp:
        - created_at: "2026-03-10T04:59:30Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5TdUnsBXCsAARAAxfv/7tk6dCuKrLNkvv+rz5NB7QStTxG9kijqM4PxYWAw
            Ky05FnlCQZpnpBG9QsxkA86z7Kx8rt8TzRZGLNkS07XjW/TmAErB99zvYX4vNOwe
            SXSSMW03FLcwSGX7+4bjsIXHTK+PnELAtRSgMRBCZo484nSHDMrEf+qp0fG6NB+9
            6Y+1egGBUYO5eD21t2xmuY0HAmdLl7MHVoClg/BHBdzYqqUUPskz3RJqPuwt0J8C
            +KEqm6Ec5u8zmi43GOSQ2lPPuMnzqo+1FdYffyNqA42iBabZSMeTacxFjvBjXKno
            U1AOcIXNNW+vOkYF9ai9pyegMviHirjcmO+06ABB2b32KmPPEhn94D6pNfJjAToz
            cMjKn9IowhM8GtS5gLtrR1DQ6xNl8yFsPZd/LlCfRY7fJx9w99V9uO+A6ePnPdeQ
            XBYVK4+CRniwZCOn2WcWITyQoXaWDsiwiqeDJUwqROb2QKW1nxQr3NZZwOLDVW1i
            9deDN2zZlEZsujWTWyJMFBA1+1aKLgzONZFdv1T9GVMqOKTS9c5tcdUzuLBWFcuh
            PtFn/RKkuHSRoua6xuMS0JUQDojlherZAhHkzm9CusaC2zhQXJmY/W1gV4WFBK/m
            ZfFf7riqjJtsv8zsfTqEHADrMuKRV8kVOshtxVOCryQCD3dfQJaE2ek3/CJxGmvS
            XgHKg4YetDxbAIZ41QaYO4n6PWybcDzBaM3wia1YvJLsco4hWyUqcW4enebglwfo
            o8U5XrUnBRaNXzoOmIqqG4dIqiurOiwVUqBPsSh6AGHZlDN5Hfq49VPkfgMyBrQ=
            =OqZE
            -----END PGP MESSAGE-----
          fp: BB0ED0CE71E0563ECF6C6F74D4B198B463FEB92F
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
