apiVersion: v1
kind: Secret
metadata:
    name: authentik-postgresql
    namespace: authentik
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:wORq+s9yssrOg7VgSls83cS6rao=,iv:j8KK65GaVRc4KCVwEXXuNl87of6LK881DNVrMn3yyDQ=,tag:2jr8Gu15rG2a7gq1y0n2Og==,type:str]
sops:
    lastmodified: "2026-03-10T04:48:41Z"
    mac: ENC[AES256_GCM,data:TzKLxnQ2bxxq3RfwZtUTurKSbLQCq2o3wAlsd6vgHY5jRSLBMIQRmJdI94LIoHCP3m3uGGXqtrPRbtgmUvn5e+yyY+dlmwsVdUvOQwR8H2uGOkcVN9du9yxvDwu9IkMYSthM95bodwKW7907pMBmie/cWR7+eSe8o7SYM6BjErQ=,iv:4CVJRLHct9vG7PvBBupETgJKlU7wBpROgpjvqol1Xl8=,tag:jeF78bufclHdhNCa5oBxTA==,type:str]
    pgp:
        - created_at: "2026-03-10T04:48:41Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5TdUnsBXCsAAQ//cXJgp4a0OEkT1P3LZmziHQda2RBKQz8SgacvEuTMjzSR
            axpnv3xJuL9DY/2jJv/mW0OyUsIecKQwIocyuaVwIYn7My0sA11MFFDUSV8YyOcj
            7qMOKljwzfQOtdyK7CmXiZLGsGfNBcdcq2zxq8Fy5zfQ8jntcIRQHKL9l5/h6OyZ
            zagxb2ucxDIBrtwAYB+ctlouJwt0UQWED5Cwrn6cCCxPkzxQdqJWHnr0rKgXLV74
            +1b8hxLPj7YJcJgcH2UJRckW4NW57gp2VxskeXNDhEBzWe9lT3ZNY7lQLCqbLukk
            INDVv/q0wGcmTTbyeenMlCGExUB8nobqm6eTo7/6IQNjEun2lkBofZV78t9Kj65e
            2NlJbiwX3xdmwL9jci6iaysRcNluRgNa30Rsz86eqpT+bPjQs3Z1NSCrgB2AHywU
            bUevGR3X6XsEfCTAFDZjdI2ekVKN4GBfr/0U4ferCgG5gK+cUR8Mh9l97NxDHNEk
            I+V7WTczuJnVypikpzHS1Hy0drE3qFkwB3MMggfg8wWVQ0RngRXq+s6g0d3/VMIb
            Gkh6nXC6BzwOHoiEGbzscO6H9N7Vfk9FhU8yMZsWpAvq2kOa5VXbH3j64jNKvAr0
            B8zXFNJJ4W+H62HZZFNm8K2NT+Cjpe6F6PwN0KBPW9FjKHnqFkhw0MhdGNgIgvnS
            XgEH1uQlnoAnu5ZdBupIuK+sxn0RGwXPu3Je/qXtLX+dzKpEFI52JAdcFO7O48IM
            T48P13/d+5Sa/7ghGML2kQ/BfGHnewWjPAWObdDTBO9uidIsW8PN7G5nbxvcXO8=
            =Xgc9
            -----END PGP MESSAGE-----
          fp: BB0ED0CE71E0563ECF6C6F74D4B198B463FEB92F
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
