apiVersion: v1
kind: Secret
metadata:
    name: authentik-config
    namespace: authentik
type: Opaque
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:6G+LnSfkwkglPfzG/Ej7ug/aEMw=,iv:G8EMf/qIZwQdRPWlzREv9GChrutesrZW6mPUD93gu7I=,tag:1GjN/rn2G28MwBXM9eA/yA==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:1ZkBo+3tvHl93QrQeLPUgGsjJJk=,iv:i901SPfmXhAkV5i9YkEMW9ma7h4BCIuIZO2vmcjkmSs=,tag:tSk20VU+dPp6WRdJfexClg==,type:str]
sops:
    lastmodified: "2026-03-10T04:48:32Z"
    mac: ENC[AES256_GCM,data:UbAXSCx122iMYDWW5aYtTJIej3DPYMccEX5df2zH7cKZPii0X0rME9iBQF+3ym2AD7MvBCLZhdOqZpVPDqtJRmJw+pQms4AjrhnLdQEpNK56MoE5olX/po2IezlrqUfhTOJzQgOHHXgTCN0c8d1OzwH3xzdLiub0+ZlPh37VYgE=,iv:WaNEQQMOMOv5b/wq8XXotAwjdQd+cIyC9WOL09zmpzs=,tag:L96IVvU4rmOYdcmYFHD/nA==,type:str]
    pgp:
        - created_at: "2026-03-10T04:48:32Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5TdUnsBXCsAAQ/+O2gjB1OhlKA683kFxomLUzTbxbYzv81/gcWrYhOqKbqB
            EH1QMZIA0o4rfRupatXwT+QYrcb5VKCeJwyeCaQebpY64eZLVL1UGAW8r8rjgB7s
            AfnVGRQQ6u6juxg28uD/j3RcBCk9AIJtz5wZ5sEkeY2efHOClI178KnN2jQey01A
            2Q7R5ZDjccLkkDjQT0cPvRBXjGhIjeUz5GuUBfIhEM25/TW8y175h8TRMH4/S37g
            h/xy/qddPaRlgk+nXisSPcTQP/K+7Q8ha5tCSnxlNAyKlTb/B/tgxhD5cES9PQf/
            pnXyWgVEg70Y/DPgVMqp0wQpzBm//kovPhIKgjymjPJSegNJrytoYoQCXSu2Td4j
            FCYmayTlW9wvWkQOVkWLxioJE2aXBVDFXtZasYowDOiQ6BU7TSvASxQnREM3txAA
            Xu+Q5X9fAKCB5lMaK95puTCMK+ob/KhaTH8YR6Mq0XnTcHM3DBZ88+6yusPwrnNK
            93kqRMa0XRJYDxVtLAVtnKM+qn5NmFOMtACzf2F17H23h4UxCL2kmB42ajiLGKOL
            Yie6hYoPvTxvH9Ryhej4koMxl+NSip1p9CpZe6pFVl5fan0GohGPlWC1tuu7rzYE
            QeSx66GCyKmkqvh6OQ/53Bqjvmf62bd+jLrgZYVKeMAHZlHl/Gu010C4aws2JB/S
            XgHbvnrIZBMddRjhj1YGp8Wys9hZ/NO9kHDuKIvw7oGZPYTr090WKgHpKV/JO2Jc
            RWUikMEyUQGv8Sdqd6eGb4Ceqq2CaZ2wh8VjrVP35v2fTvj7opZWRA1D4QK5gfc=
            =dvwG
            -----END PGP MESSAGE-----
          fp: BB0ED0CE71E0563ECF6C6F74D4B198B463FEB92F
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
