apiVersion: cdi.kubevirt.io/v1beta1
kind: CDI
metadata:
  name: cdi
  namespace: kubevirt
spec:
  config:
    podResourceRequirements:
      limits:
        memory: 2Gi
      requests:
        memory: 256Mi