apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: kubevirt
spec:
  configuration:
    developerConfiguration:
      useEmulation: false
    permittedHostDevices:
      pciHostDevices:
        - pciVendorSelector: "1002:150e"
          resourceName: "devices.kubevirt.io/amd-igpu"
        - pciVendorSelector: "1002:1640"
          resourceName: "devices.kubevirt.io/amd-igpu-audio"