apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: grafana-k8s-monitoring
    namespace: grafana
spec:
    interval: 30m
    chart:
        spec:
            chart: k8s-monitoring
            version: '>=4.0.0 <5.0.0'
            sourceRef:
                kind: HelmRepository
                name: grafana
                namespace: grafana
    install:
        remediation:
            retries: 3
    upgrade:
        remediation:
            retries: 3
    values:
        cluster:
            name: linus
        destinations:
            grafana-cloud-metrics:
                type: prometheus
                url: https://prometheus-prod-67-prod-us-west-0.grafana.net./api/prom/push
                auth:
                    type: basic
                    username: "3145678"
                    password: ENC[AES256_GCM,data:EuXAfgkhB3FONJgqR/1XGT2HrjxTYD7T3pcDRVZ99O35QaY1t/SRhwCyyUkJDFOOiRWlLuZg27EzNcEPMrpF641HPVZ2SJsEmIiz3cWA6YbUilP4wDAXMnNUcNbHX7aR/J6RHp9W+CqhzU5MxVnNuQ6Dhq4CBVJwzc6pKhJNpMW9PK7lp0fVziH4DiHdbfvAM2PCY2xjXqp+HoXH4fySHA==,iv:icHcK5hW4I55Phaq1/LKJEAwohNUo3ElUij+bgBAFlY=,tag:oq7ZflRjuxnMje08icbIQw==,type:str]
            grafana-cloud-logs:
                type: loki
                url: https://logs-prod-021.grafana.net./loki/api/v1/push
                auth:
                    type: basic
                    username: "1568514"
                    password: ENC[AES256_GCM,data:eONJ6u1aIsbxUa9Oy/Fasw/N1SZL6SXsapuUrmBFEzi/69MqK2xLWhIwCaKzIv84L9X1ROJmqj1Ggj+L7SwVX8dpWALAMhhP4HukT1UMz85QBy+JDzXDJaN/enDV4gQOm6eT/o1izT5zSvajRnIXBDVw3bV7bYVA014f7skCwnXNvt/fAvXBJ1LT1WFWhLJd9BIccr/yg6aZJ2W8wkax1A==,iv:SwpVmLrcTBlu8Q6gKf8YyO/OPm2j2YFKwxYUrxXZPhY=,tag:Vw9rAlHPn96NGeVkLVBvZQ==,type:str]
        clusterMetrics:
            enabled: true
            collector: alloy-metrics
        hostMetrics:
            enabled: true
            collector: alloy-metrics
            linuxHosts:
                enabled: true
            windowsHosts:
                enabled: true
        annotationAutodiscovery:
            enabled: true
            collector: alloy-metrics
        clusterEvents:
            enabled: true
            collector: alloy-singleton
        podLogsViaLoki:
            enabled: true
            collector: alloy-logs
        integrations:
            collector: alloy-metrics
            alloy:
                instances:
                    - name: alloy
                      labelSelectors:
                        app.kubernetes.io/name:
                            - alloy-metrics
                            - alloy-singleton
                            - alloy-logs
        collectors:
            alloy-metrics:
                presets:
                    - clustered
                    - statefulset
            alloy-singleton:
                presets:
                    - singleton
            alloy-logs:
                presets:
                    - filesystem-log-reader
                    - daemonset
        telemetryServices:
            kube-state-metrics:
                deploy: true
            node-exporter:
                deploy: true
            windows-exporter:
                deploy: true
sops:
    lastmodified: "2026-07-13T00:00:30Z"
    mac: ENC[AES256_GCM,data:0SXK8tn3vrLuugsOfeCNqE8K7Nc+ZrAeyE9B9KKQPLns7/udG5qT+jXi599pJY7h5HusecnvDMYGogXiERWpMQvaB+icHTakrHpvkkerGKvlsG6/qv7Y/Aql4V6foC2Oykty2bDs1kfnxJMWcn3mfrlDv/pbcD5icE3hStUvnOw=,iv:NDUdrNDRitfglOWpHaRrSONC7nb3jBpGi97zTqYEi6I=,tag:VDdtluf1SwET3D5o65+u5A==,type:str]
    pgp:
        - created_at: "2026-07-13T00:00:30Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5TdUnsBXCsAARAAyv8LhXlnn8jSno8QSihfKa4lRTRscnMUXrMuMl6vcZsQ
            x3USLE57ImzjJeEF0QVPg2IwBg1JPRwFJdS4fKTgI1rCpwusTP6d0/Mz7tvCGiCn
            6YQ0QqdLayJwfJMS/uwbvKZh0LpFNj4DWSXrBtJF0NQZN2x02ql3l5F7OSl66dWy
            g977Vv5cIcIZBCL2Xc+2U1S3ZJGGIai7RYPshcihIInHF8+Gz0NaM6PzlJ+FwVb0
            U2V9/OoNwMXnkQBU8DLPNHd3WL0q/iIFpwDuouB5LBbznpJcnDWiKqhtgDo0D8ok
            U2/rSdiR5cGQZbX54bWAEtD+u05bVAg+/vZejvPdiWhLlkyyDdvbQ2Y0Qg5rWXra
            5pEOuZQ212dtmSDIChxijjuyGB6HipJ92Tb6DU1hiR73L1BzXw22ag8NJl99kBw4
            rASF0lPBsNCX2piJsTUeelHWBCZg/HJl/4ofLkKr1ddqRTG+27uncAl/60RV90Eo
            A8kHaXP2Q3kF0TmpGSNry3Fq1hEI4kQ4W7xvSzvJpQGtRC9qe3F9kLxSbab/WIFk
            cDaPn7ep1To8wcKF2MbtHLruG0KByjkfp1f0M8z1TYOGwYIG/149ZJ7UY1GCzuzZ
            nz7hcud6/r02VDTxc5nHpEfydYiRGiOUq2Sjwu2pd5G9IqslX4gFtYazwu6D9rjS
            XgGzSNZ62PjspvptCoJVxbnpBNARmyCQinxGtHIqxt/fXktaQ0Tm49T6GI5OGP2Z
            5GGFVoI9WTNhxaXUZuEPGkL3kMN7Xr7nawnL0xzWXqMhpJR9HDtKrBIGnzOWUxA=
            =nT3r
            -----END PGP MESSAGE-----
          fp: BB0ED0CE71E0563ECF6C6F74D4B198B463FEB92F
    encrypted_regex: ^password$
    version: 3.12.1
