apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: windows-10-iso
spec:
  source:
    http:
      url: http://vm-image-server.cdi.svc/en-us_windows_10_consumer_editions_version_22h2_updated_oct_2025_x64_dvd_38efd00d.iso
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
    storageClassName: zfs-local-zvol
---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: virtio-iso
spec:
  source:
    http:
      url: https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/stable-virtio/virtio-win.iso
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: zfs-local-zvol
---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: alpine-iso
spec:
  source:
    http:
      url: http://vm-image-server.cdi.svc/alpine-standard-3.20.3-x86_64.iso
  pvc:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 300Mi
    storageClassName: zfs-local-zvol