apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: cirros
  namespace: default
spec:
  source:
    http:
      url: http://vm-image-server.cdi.svc/cirros-0.6.2-x86_64-disk.img
  pvc:
    accessModes:
      - ReadWriteOnce
    storageClassName: zfs-local-zvol
    volumeMode: Block
    resources:
      requests:
        storage: 1Gi
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: cirros
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: cirros
    spec:
      domain:
        cpu:
          cores: 1
        resources:
          requests:
            memory: 128Mi
        devices:
          disks:
            - name: rootdisk
              disk:
                bus: virtio
      volumes:
        - name: rootdisk
          dataVolume:
            name: cirros