apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: windows-rootdisk
spec:
  source:
    blank: {}
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 200Gi
    storageClassName: zfs-local-zvol
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: windows
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: windows
    spec:
      domain:
        machine:
          type: q35
        cpu:
          cores: 4
          model: host-passthrough
        resources:
          requests:
            memory: 8Gi
        devices:
          disks:
            - name: windows-10-iso
              cdrom:
                bus: sata
              bootOrder: 1
            - name: virtio-iso
              cdrom:
                bus: sata
              bootOrder: 2
            - name: rootdisk
              disk:
                bus: virtio
              bootOrder: 3
          interfaces:
            - name: default
              masquerade: {}
          gpus:
            - name: gpu0
              deviceName: devices.kubevirt.io/amd-igpu
        features:
          kvm:
            hidden: true
          hyperv:
            relaxed:
              enabled: true
            vapic:
              enabled: true
            spinlocks:
              enabled: true
              spinlocks: 8191
      networks:
        - name: default
          pod: {}
      volumes:
        - name: windows-10-iso
          dataVolume:
            name: windows-10-iso
        - name: virtio-iso
          dataVolume:
            name: virtio-iso
        - name: rootdisk
          dataVolume:
            name: windows-rootdisk