apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: ubuntu-26-graphical
spec:
  source:
    http:
      url: http://vm-image-server.cdi.svc/ubuntu-26.04-desktop-amd64.iso
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
    storageClassName: zfs-local-zvol