apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: ubuntu-26
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/vm: ubuntu-26
    spec:
      domain:
        cpu:
          cores: 2
        memory:
          guest: 4Gi
        devices:
          disks:
            - name: rootdisk
              bootOrder: 1
              disk:
                bus: virtio
            - name: cdrom
              bootOrder: 2
              cdrom:
                bus: sata
                readonly: true
          interfaces:
            - name: default
              masquerade: {}
      networks:
        - name: default
          pod: {}
      volumes:
        - name: rootdisk
          dataVolume:
            name: ubuntu-26-root
        - name: cdrom
          dataVolume:
            name: ubuntu-26-graphical
---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: ubuntu-26-root
spec:
  source:
    blank: {}
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 80Gi
    storageClassName: zfs-local-zvol
