apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  interval: 30m
  chart:
    spec:
      chart: jellyfin
      version: 3.2.0
      sourceRef:
        kind: HelmRepository
        name: jellyfin
        namespace: jellyfin
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    replicaCount: 1

    image:
      pullPolicy: IfNotPresent

    persistence:
      config:
        enabled: true
        type: pvc
        size: 5Gi
        storageClass: zfs-local-dataset
      media:
        enabled: true
        type: hostPath
        hostPath: /tank/media
      cache:
        enabled: true
        type: pvc
        existingClaim: jellyfin-cache

    ingress:
      enabled: false
        
    service:
      type: LoadBalancer
      port: 8096

    volumes:
      - name: dri
        hostPath:
          path: /dev/dri
          type: Directory

    volumeMounts:
      - name: dri
        mountPath: /dev/dri

    nodeSelector: {}
    tolerations: []
    affinity: {}
